### ISSUE TITLE
python3 experiments/inference.py error

### ISSUE THREAD

**Issue by terrs** [markshih91/mobilenet_v2_ssdlite_keras#9]
tensorflow            2.4.0 
keras                     2.4.3

KerasTensor(type_spec=TensorSpec(shape=(None, 2268, 81), dtype=tf.float32, name=None), name='ssd_mbox_conf_softmax/truediv:0', description="created by layer 'ssd_mbox_conf_softmax'")
KerasTensor(type_spec=TensorSpec(shape=(None, 2268, 4), dtype=tf.float32, name=None), name='ssd_box/concat:0', description="created by layer 'ssd_box'")
KerasTensor(type_spec=TensorSpec(shape=(None, 4000, 8), dtype=tf.float32, name=None), name='ssd_priorbox/concat:0', description="created by layer 'ssd_priorbox'")
Traceback (most recent call last):
  File "experiments/inference.py", line 42, in <module>
    model = mobilenet_v2_ssd(image_size, n_classes, mode, l2_regularization, min_scale, max_scale, scales,
  File "/Users/xx/Work/AI/TF/code/mobilenet_v2_ssdlite_keras/models/keras_mobilenet_v2_ssdlite.py", line 386, in mobilenet_v2_ssd
    predictions = Concatenate(axis=0, name='ssd_predictions')([cls, box, priorbox])
  File "/Users/xx/.conda/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 951, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "/Users/xx/.conda/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1090, in _functional_construction_call
    outputs = self._keras_tensor_symbolic_call(
  File "/Users/xx/.conda/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 822, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/Users/xx/.conda/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 862, in _infer_output_signature
    self._maybe_build(inputs)
  File "/Users/xx/.conda/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2710, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "/Users/xx/.conda/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/keras/utils/tf_utils.py", line 272, in wrapper
    output_shape = fn(instance, input_shape)
  File "/Users/xx/.conda/envs/tensorflow/lib/python3.8/site-packages/tensorflow/python/keras/layers/merge.py", line 519, in build
    raise ValueError(err_msg)
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 2268, 81), (None, 2268, 4), (None, 4000, 8)]

**Comment by ChingLeung-1** [comment]
I have got the same issue too

**Comment by stu-zhangxl** [comment]
I have got the same issue too, how can I correct this error?
